version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/db_noel_betest
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: db_noel_betest
    ports:
      - "27017:27017"

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_noel_betest
    ports:
      - "6379:6379"